version: "3.9"
services:
  bun-backend:
    container_name: bun-backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    expose:
      - 4000:4000
    ports:
      - 4000:4000
    restart: always
    environment:
      - NODE_ENV=dev
      - PORT=4000
      - DB_CONNECTION_PASS=bun2023!*
      - DB_CONNECTION_USER=root
      - DB_CONNECTION_NAME=bun
      - DB_CONNECTION_URI=mongodb://mongodb:27017
    mem_limit: 2g

networks:
  backend:
    driver: bridge
volumes:
  mongodb-data:
